/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sgt.view;

import com.sgt.db.DaoClass;
import java.awt.Color;
import java.sql.Connection;
import java.util.Locale;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author maste
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.getContentPane().setBackground(Color.decode("#009688"));
        this.setLocationRelativeTo(null);
    }
    
     private void CallRel() throws JRException {                                         
        Connection Conn = DaoClass.conectar();             
        JasperPrint print = null;         
        print = JasperFillManager.fillReport("C:\\SGT\\relJasper\\relEstudanteFull.jasper", null, Conn);
        JasperViewer.viewReport(print, false, Locale.US);                
    } 
     
    public void setNames(Map Nomes){       
        jlNome.setText((String) Nomes.get("Nome".toString()));
        jlCir.setText((String) Nomes.get("Cir".toString()));
        jbCong.setText(Nomes.get("Cong").toString());  
    } 
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        areaDesktop = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jlNome = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbCong = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlCir = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFMM = new javax.swing.JMenu();
        itemFSMM = new javax.swing.JMenuItem();
        addEstudante = new javax.swing.JMenuItem();
        callUser = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemProg = new javax.swing.JMenuItem();
        estudantesConsulta = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        relEstudantes = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        preferencias = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SGT - Menu Principal");
        setResizable(false);

        areaDesktop.setBackground(new java.awt.Color(7, 127, 145));

        javax.swing.GroupLayout areaDesktopLayout = new javax.swing.GroupLayout(areaDesktop);
        areaDesktop.setLayout(areaDesktopLayout);
        areaDesktopLayout.setHorizontalGroup(
            areaDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        areaDesktopLayout.setVerticalGroup(
            areaDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 645, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bem vindo:");

        jlNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlNome.setForeground(new java.awt.Color(255, 255, 255));
        jlNome.setText("Henrique Rocha");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Congregação: ");

        jbCong.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbCong.setForeground(new java.awt.Color(255, 255, 255));
        jbCong.setText("Jardim Alvorada");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Circuito: ");

        jlCir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlCir.setForeground(new java.awt.Color(255, 255, 255));
        jlCir.setText("BA - 034");

        menuFMM.setText("Novo");
        menuFMM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFMMActionPerformed(evt);
            }
        });

        itemFSMM.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        itemFSMM.setText("Programa faça seu melhor no ministério");
        itemFSMM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemFSMMActionPerformed(evt);
            }
        });
        menuFMM.add(itemFSMM);

        addEstudante.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        addEstudante.setText("Estudante");
        addEstudante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEstudanteActionPerformed(evt);
            }
        });
        menuFMM.add(addEstudante);

        callUser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        callUser.setText("Usuário");
        callUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                callUserActionPerformed(evt);
            }
        });
        menuFMM.add(callUser);

        jMenuBar1.add(menuFMM);

        jMenu2.setText("Consulta");

        itemProg.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        itemProg.setText("Programação");
        itemProg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemProgActionPerformed(evt);
            }
        });
        jMenu2.add(itemProg);

        estudantesConsulta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        estudantesConsulta.setText("Estudantes");
        estudantesConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estudantesConsultaActionPerformed(evt);
            }
        });
        jMenu2.add(estudantesConsulta);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Relatórios");

        relEstudantes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        relEstudantes.setText("Estudantes");
        relEstudantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relEstudantesActionPerformed(evt);
            }
        });
        jMenu1.add(relEstudantes);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Programa");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Configurações");

        preferencias.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        preferencias.setText("Preferências");
        preferencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preferenciasActionPerformed(evt);
            }
        });
        jMenu3.add(preferencias);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Ajuda");
        jMenuBar1.add(jMenu4);

        jSair.setText("Sair");
        jSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSairMouseClicked(evt);
            }
        });
        jSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSairActionPerformed(evt);
            }
        });
        jMenuBar1.add(jSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jlNome, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jbCong)
                .addGap(48, 48, 48)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jlCir)
                .addContainerGap(623, Short.MAX_VALUE))
            .addComponent(areaDesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jlNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addComponent(jbCong)
                    .addComponent(jLabel5)
                    .addComponent(jlCir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(areaDesktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addEstudanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEstudanteActionPerformed
       CadastraEstudante CallTelaCE = new CadastraEstudante();
       CallTelaCE.setVisible(true);
       areaDesktop.add(CallTelaCE);
    }//GEN-LAST:event_addEstudanteActionPerformed

    private void callUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_callUserActionPerformed
       CadastroUsuario CallTelaUser = new CadastroUsuario();
       CallTelaUser.setVisible(true);
       areaDesktop.add(CallTelaUser);
    }//GEN-LAST:event_callUserActionPerformed

    private void estudantesConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estudantesConsultaActionPerformed
        ConsultaEstudantes CallWindow = new ConsultaEstudantes();
        CallWindow.setVisible(true);
        CallWindow.getContentPane().setBackground(Color.decode("#009688"));
        CallWindow.setLocationRelativeTo(null);
    }//GEN-LAST:event_estudantesConsultaActionPerformed

    private void jSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSairActionPerformed
       
    }//GEN-LAST:event_jSairActionPerformed

    private void jSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jSairMouseClicked

    private void itemProgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemProgActionPerformed
        ConsultaFSeuMelhor CallWindow = new ConsultaFSeuMelhor();
        CallWindow.setVisible(true);
        areaDesktop.add(CallWindow);
    }//GEN-LAST:event_itemProgActionPerformed

    private void menuFMMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFMMActionPerformed

    }//GEN-LAST:event_menuFMMActionPerformed

    private void itemFSMMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemFSMMActionPerformed
        NovoProgramaFSeuMelhor callTela = new NovoProgramaFSeuMelhor();
        callTela.setVisible(true);
        areaDesktop.add(callTela);
    }//GEN-LAST:event_itemFSMMActionPerformed

    private void preferenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preferenciasActionPerformed
        PreferenciasClass CallTelaP = new PreferenciasClass();
        CallTelaP.setVisible(true);
        areaDesktop.add(CallTelaP);
    }//GEN-LAST:event_preferenciasActionPerformed

    private void relEstudantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relEstudantesActionPerformed
        try {
            CallRel();
        } catch (JRException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_relEstudantesActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       Periodo CallPer = new Periodo();
       CallPer.setVisible(true);
       CallPer.setLocationRelativeTo(this);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addEstudante;
    private javax.swing.JDesktopPane areaDesktop;
    private javax.swing.JMenuItem callUser;
    private javax.swing.JMenuItem estudantesConsulta;
    private javax.swing.JMenuItem itemFSMM;
    private javax.swing.JMenuItem itemProg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu jSair;
    private javax.swing.JLabel jbCong;
    private javax.swing.JLabel jlCir;
    private javax.swing.JLabel jlNome;
    private javax.swing.JMenu menuFMM;
    private javax.swing.JMenuItem preferencias;
    private javax.swing.JMenuItem relEstudantes;
    // End of variables declaration//GEN-END:variables
}
